baseURL = 'https://blog.yfstudio.online/' # 以后换成你的域名
locale = 'zh-cn'                          # 改成中文 locale
defaultContentLanguage = "zh"
hasCJKLanguage = true                     # 站点含中日韩内容，影响字数统计
enableRobotsTXT = true                    # 生成 robots.txt
title = '依凡的记事本'                         # 站点标题
theme = 'PaperMod'                        # ← 这行必须加

[outputs]
home = ['HTML', 'RSS', 'JSON'] # 搜索功能需要 index.json

[params]
env = 'production'          # 启用 OG/Twitter Cards/Schema
title = '依凡的记事本'
description = 'YF 的个人博客'
keywords = ['Blog', 'Tech']
author = 'YF'
DateFormat = '2006-01-02'   # 日期显示格式
defaultTheme = 'dark'       # light / dark / auto
disableThemeToggle = false  # 是否禁止用户切换明暗主题

ShowReadingTime = true                # 显示阅读时间
ShowShareButtons = false              # 关闭分享按钮
ShowPostNavLinks = true               # 文章底部的上一篇/下一篇
ShowBreadCrumbs = true                # 面包屑导航
ShowCodeCopyButtons = true            # 代码块复制按钮
ShowWordCount = true                  # 显示字数
ShowRssButtonInSectionTermList = true
UseHugoToc = false                    # false=用 PaperMod 自己的 TOC（默认），true=用 Hugo 内置的
ShowToc = true                        # 显示目录
TocOpen = false                       # 是否默认展开

[params.footer]
text = '<a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备2024186230号</a>'

[params.homeInfoParams]
title = '👋 你好，我是依凡'
content = '如果你认识我，你会知道我平平无奇。如果你了解我，你会发现我相当有趣。'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/yzyf1312'

[[params.socialIcons]]
name = 'rss'
url = '/index.xml'

[[menu.main]]
identifier = 'archives'
name = '归档'
url = '/archives/'
weight = 10

[[menu.main]]
identifier = 'categories'
name = '分类'
url = '/categories/'
weight = 20

[[menu.main]]
identifier = 'tags'
name = '标签'
url = '/tags/'
weight = 30

[[menu.main]]
identifier = 'search'
name = '搜索'
url = '/search/'
weight = 40

[markup]
[markup.highlight]
noClasses = false
lineNos = true
style = 'monokai'
